#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana
- name: Install dependencies
  apt:
    name:
      - gnupg
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Grafana GPG key
  apt_key:
    url: "{{ grafana_gpg_key }}"
    state: present
    validate_certs: no

- name: Add Grafana repository
  apt_repository:
    repo: "{{ grafana_repo }}"
    state: present
    validate_certs: no

- name: Install Grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Wait for Grafana service to start
  uri:
    url: "http://127.0.0.1:{{ grafana_port }}"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Check if admin password is already set
  uri:
    url: "http://admin:{{ grafana_admin_password }}@127.0.0.1:{{ grafana_port }}/api/user"
    method: GET
    force_basic_auth: yes
    status_code: 200
  register: __grafana_auth_check
  ignore_errors: yes
  changed_when: false

- name: Change Grafana admin password
  shell: "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  when: __grafana_auth_check.status != 200