#SPDX-License-Identifier: MIT-0
---
# tasks file for jenkins
- name: Add Jenkins GPG key
  apt_key:
    url: "{{ jenkins_key_url }}"
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb {{ jenkins_repo_url }} binary/"
    state: present

- name: Install Java and Jenkins
  apt:
    name: "{{ jenkins_packages }}"
    state: present
    update_cache: yes

- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes