#SPDX-License-Identifier: MIT-0
---
# defaults file for docker
docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - unzip
  - python3-docker
docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
docker_compose_version: "1.29.2"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
docker_users:
  - ubuntu
  - jenkins
