#SPDX-License-Identifier: MIT-0
---
# tasks file for sonarqube
- name: Run SonarQube (LTS Community Edition)
  community.docker.docker_container:
    name: sonarqube
    image: "{{ sonarqube_image }}"
    pull: true
    state: started
    restart_policy: always
    ports: "{{ sonarqube_ports }}"
    volumes:
      - "{{ sonarqube_data_volume }}:/opt/sonarqube/data"
      - "{{ sonarqube_extensions_volume }}:/opt/sonarqube/extensions"
      - "{{ sonarqube_logs_volume }}:/opt/sonarqube/logs"