---
- name: Set folder permissions for prometheus user
  file:
    path: "{{ prometheus_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    recurse: yes
    
- name: Copy systemd service for prometheus
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/