---
- name: Create Prometheus directory
  file:
    path: "{{ prometheus_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Download and extract Prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: "{{ prometheus_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"