#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus
# prometheus/tasks/main.yml
---
- include: create_user.yml
- include: install.yml
- include: configure.yml
- include: prometheus_status.yml