#SPDX-License-Identifier: MIT-0
---
# defaults file for grafana
grafana_admin_password: "your_admin_password"
grafana_gpg_key: "https://packages.grafana.com/gpg.key"
grafana_repo: "deb https://packages.grafana.com/oss/deb stable main"
grafana_port: 3000